[package]
version = "0.1.0"
name = "Real_time_ltv-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.1.0"
fibonacci-lib = { path = "../lib" }
hex = "0.4.3"
